version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: src/Dockerfile.react
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src

  express-server:
    build:
      context: .
      dockerfile: src/server/Dockerfile.server
    ports:
      - "3001:3001"
    volumes:
      - ./src:/app/src
    environment:
      NODE_ENV: development
      OPENAI_API_KEY: ${OPENAI_API_KEY}