name: Build

on:
  push:
    branches:
      - deployment/ci # Switch to main before merging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t liran86/ai_debugger_frontend:${{ github.sha }} -f src/config/Dockerfile .
