name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install EB CLI
        run: pip install awsebcli --upgrade --user

      - name: Add EB CLI to PATH
        run: echo 'export PATH=$PATH:$HOME/.local/bin' >> $GITHUB_ENV

      - name: List current directory contents
        run: ls -la
      
      - name: Create a zip file of the build artifacts
        run: zip -r app.zip . build
      
      - name: Deployment
        run: |
          # Initialize EB and deploy
          eb init -p node.js -r ${{ secrets.AWS_REGION }} ${{ secrets.EB_APPLICATION_NAME }}
          eb use ${{ secrets.EB_ENVIRONMENT_NAME }}
          eb deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: ./build
