name: Deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install
      
      - name: Build React app
        run: npm run build

      - name: Deploy
        run: |
          npm install -g elastic-beanstalk-cli # Install EB CLI
          eb init -p node.js -r $AWS_REGION $EB_APPLICATION_NAME # Initialize EB
          eb use $EB_ENVIRONMENT_NAME # Use the desired environment
          eb deploy --staged # Deploy the application
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          EB_APPLICATION_NAME: ${{ secrets.EB_APPLICATION_NAME }}
          EB_ENVIRONMENT_NAME: ${{ secrets.EB_ENVIRONMENT_NAME }}
        working-directory: ./build
