# deploy.yml

name: Deploy

on:
  push:
    branches:
      - deployment/ci

jobs:
  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker tag liran86/ai_debugger_frontend:${{ github.sha }} liran86/ai_debugger_frontend:latest
          docker push liran86/ai_debugger_frontend:${{ github.sha }}
          docker push liran86/ai_debugger_frontend:latest
