name: Test

on:
  push:
    branches:
      - deployment/ci

jobs:
  test:
    runs-on: ubuntu-latest

    needs: build

    if: false  # disable tests.

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
